### ISSUE TITLE
T:Connect Patcher

### ISSUE THREAD

**Issue by Miquest** [jwoglom/pumpX2#8]
Hi, 
I'm working with another developer on a T: Connect APK Patcher, that allows to install the T: Connect Application on a not supported device.
I would be very happy if you would test our patch on your pump, I'm not able to because in my country (Germany), the update isn't available yet...

Kind regards,
Thorin E.

**Comment by jwoglom** [comment]
hey, send me an email (address should be on my GitHub profile) and I will take a look. Feel free to join the Nightscout/wearenotwaiting discord in the #tslim-x2-dev channel as well if you need more testers: https://discord.gg/KyZGdhyt44
